server:
  port: 8083

spring:
  application:
    name: order-service  # Nom du service qui sera enregistré
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5433/order  # Base de données pour le service order
    password: 11200228
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/  # URL du serveur Eureka

