server:
  port: 8082

spring:
  application:
    name: product-service  # Nom du service qui sera enregistré
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5433/product  # Base de données pour le service product
    password: 11200228
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

    cloud:
      config:
        uri: http://localhost:8888  # URL de votre Config Server
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/  # URL du serveur Eureka
